version: "3.9"
services:
    alpine:
        env_file: .env
        container_name: ${CONTAINER_NAME}
        build:
            context: .
            dockerfile: config/docker/Dockerfile
            args:
                - ALPINE_VERSION=${ALPINE_VERSION}
                - TZ=${TZ}
        volumes:
            - "./logs:/srv/docker-alpine/logs"
#        ports:
#            - ${HOST_PORT}:${CONTAINER_PORT}
        restart: unless-stopped
